# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      exclude:
        - "ministryofjustice/*"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"

  - package-ecosystem: "helm"
    directory: "/helm_deploy/licences"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  - package-ecosystem: "pre-commit"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
