module.exports = [
  {
    bookingId: 1,
    offenderNo: 'A0001XX',
    firstName: 'RO Processing',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'PROCESSING_RO',
    status: 'Submitted to RO',
  },

  {
    bookingId: 2,
    offenderNo: 'A0001XX',
    firstName: 'Unstarted',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'UNSTARTED',
    status: 'Not started',
  },

  {
    bookingId: 3,
    offenderNo: 'A0001XX',
    firstName: 'Eligibility',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'ELIGIBILITY',
    status: 'Checking eligibility',
  },

  {
    bookingId: 4,
    offenderNo: 'A0001XX',
    firstName: 'Approval',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'APPROVAL',
    status: 'With decision maker',
  },

  {
    bookingId: 5,
    offenderNo: 'A0001XX',
    firstName: 'Approved',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'DECIDED',
    status: 'Approved',
  },

  {
    bookingId: 5,
    offenderNo: 'A0001XX',
    firstName: 'Refused',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'DECIDED',
    status: 'Refused',
  },

  {
    bookingId: 6,
    offenderNo: 'A0001XX',
    firstName: 'Processing CA not postponed',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'PROCESSING_CA',
    status: 'Review case',
  },

  {
    bookingId: 7,
    offenderNo: 'A0001XX',
    firstName: 'Processing CA postponed',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'PROCESSING_CA',
    status: 'Postponed',
  },

  {
    bookingId: 8,
    offenderNo: 'A0001XX',
    firstName: 'Opted out',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'ELIGIBILITY',
    status: 'Opted out',
  },

  {
    bookingId: 9,
    offenderNo: 'A0001XX',
    firstName: 'Eligible',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'ELIGIBILITY',
    status: 'Eligible',
  },

  {
    bookingId: 10,
    offenderNo: 'A0001XX',
    firstName: 'ReadyToCheck',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'PROCESSING_RO',
    status: 'Ready to check',
  },

  {
    bookingId: 11,
    offenderNo: 'A0001XX',
    firstName: 'GettingAddress',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'ELIGIBILITY',
    status: 'Getting address',
  },

  {
    bookingId: 12,
    offenderNo: 'A0001XX',
    firstName: 'AddressRejected',
    lastName: 'Test',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail: {
      bookingId: 1,
      conditionalReleaseDate: '15/10/2019',
      homeDetentionCurfewEligibilityDate: '13/07/2019',
    },
    due: { text: '1 year', overdue: false },
    stage: 'ELIGIBILITY',
    status: 'Address rejected',
  },
]
