/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/queue-admin/retry-dlq/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryDlq']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/retry-all-dlqs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryAllDlqs']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/purge-queue/{queueName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['purgeQueue']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/migrations/delete-inactive-licences/{lastIdProcessed}/{batchSize}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Migration to populate the licences table with deleted at timestamp for soft deletion
     * @description Migration to populate the licences table with deleted at timestamp for soft deletion.Requires HDC_ADMIN.
     */
    post: operations['populateDeletedAtForLicences']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/licences/reset': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Allows for bulk reset of licencesRequires HDC_ADMIN. */
    post: operations['resetLicences']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/licences/conditions/batch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retrieve bespoke conditions for a batch of licences
     * @description Returns converted bespoke conditions for the supplied licence IDs
     */
    post: operations['getBespokeConditions']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/jobs/delete-inactive-licences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Job to delete licences that are no longer active.
     * @description Job to delete licences that are no longer active.
     */
    post: operations['populateDeletedAtForLicences_1']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/subject-access-request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Provides content for a prisoner to satisfy the needs of a subject access request on their behalf
     * @description Requires role SAR_DATA_ACCESS or additional role as specified by hmpps.sar.additionalAccessRole configuration.
     */
    get: operations['getSarContentByReference']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/get-dlq-messages/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDlqMessages']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/licence/hdc/{bookingId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a licence matching the booking ID.
     * @description Returns a licence for the booking ID.Requires ROLE_HDC_ADMIN.
     */
    get: operations['getHdcLicenceByBookingId']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    RetryDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    PurgeQueueResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    MigrationBatchResponse: {
      /** Format: int32 */
      totalProcessed: number
      /** Format: int32 */
      totalDeleted: number
      /** Format: int32 */
      totalFailedToProcess: number
      /** Format: int32 */
      batchSize: number
      /** Format: int64 */
      lastIdProcessed?: number
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    ResetResponse: {
      /**
       * Format: int32
       * @description Number of licences reset in hdc
       */
      numberOfResetRecordsInHdc: number
      /**
       * Format: int32
       * @description Number of licences reset in NOMIS
       */
      numberOfResetRecordsInNomis: number
      /**
       * Format: int32
       * @description Number of resets requested
       */
      numberOfResetsRequested: number
    }
    /** @description Request containing licence IDs to retrieve bespoke conditions for */
    LicenceIdBatchRequest: {
      /**
       * @description List of licence IDs
       * @example [
       *       1,
       *       2,
       *       3
       *     ]
       */
      ids: number[]
    }
    /** @description Converted bespoke condition */
    ConvertedBespokeCondition: {
      /**
       * @description Condition code
       * @example ABC
       */
      code?: string
      /**
       * @description Condition text
       * @example You must not enter the exclusion zone.
       */
      text?: string
    }
    /** @description Batch response containing requested licence IDs and their converted bespoke conditions */
    ConvertedLicenseBatch: {
      /**
       * @description List of requested licence IDs
       * @example [
       *       12345,
       *       67890
       *     ]
       */
      ids: number[]
      /** @description List of licences with their converted bespoke conditions */
      conditions: components['schemas']['ConvertedLicenseConditions'][]
    }
    /** @description Converted licence with bespoke conditions */
    ConvertedLicenseConditions: {
      /**
       * Format: int64
       * @description Licence identifier
       * @example 12345
       */
      id: number
      /**
       * @description Prison number associated with the licence
       * @example A1234BC
       */
      prisonNumber: string
      /**
       * Format: int64
       * @description Booking identifier
       * @example 987654
       */
      bookingId: number
      /** @description List of converted bespoke conditions */
      conditions: components['schemas']['ConvertedBespokeCondition'][]
    }
    Attachment: {
      /**
       * Format: int32
       * @description The number of the attachment which will match any corresponding reference in the content section
       */
      attachmentNumber: number
      /** @description The name or description of the attachment which will be included in the report */
      name: string
      /** @description The content type of the attachment */
      contentType: string
      /** @description The url to be used to download the attachment file */
      url: string
      /**
       * Format: int32
       * @description The size of the attachment file in bytes
       */
      filesize: number
      /** @description The filename of attachment file */
      filename: string
    }
    HmppsSubjectAccessRequestContent: {
      /** @description The content of the subject access request response */
      content: unknown
      /** @description The details of any attachments for the subject access request response */
      attachments?: components['schemas']['Attachment'][]
    }
    DlqMessage: {
      body: {
        [key: string]: unknown
      }
      messageId: string
    }
    GetDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
      /** Format: int32 */
      messagesReturnedCount: number
      messages: components['schemas']['DlqMessage'][]
    }
    /** @description Describes the curfew address on a HDC licence */
    CurfewAddress: {
      /**
       * @description The first line of the curfew address
       * @example 1
       */
      addressLine1?: string
      /**
       * @description The second line of the curfew address
       * @example Off Some Road
       */
      addressLine2?: string
      /**
       * @description The town or city associated with the curfew address
       * @example Some Town
       */
      townOrCity?: string
      /**
       * @description The county associated with the curfew address
       * @example Some County
       */
      county?: string
      /**
       * @description The postcode for the curfew address
       * @example SO30 2UH
       */
      postcode?: string
      /**
       * @description The curfew address type for the person
       * @enum {string}
       */
      curfewAddressType?: 'RESIDENTIAL' | 'CAS'
    }
    /** @description Describes the curfew times on a HDC licence */
    CurfewTimes: {
      /**
       * @description The starting day for the curfew time
       * @example MONDAY
       * @enum {string}
       */
      fromDay: 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY'
      /**
       * Format: HH:mm
       * @description The starting time for the curfew
       * @example 15:00
       */
      fromTime?: string
      /**
       * @description The ending day for the curfew time
       * @example TUESDAY
       * @enum {string}
       */
      untilDay: 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY'
      /**
       * Format: HH:mm
       * @description The ending time for the curfew
       * @example 07:00
       */
      untilTime?: string
    }
    /** @description Describes the first night curfew times on a HDC Licence */
    FirstNight: {
      /**
       * Format: HH:mm
       * @description The starting time for the curfew on the first night
       * @example 19:00
       */
      firstNightFrom?: string
      /**
       * Format: HH:mm
       * @description The ending time for the curfew on the first night
       * @example 08:00
       */
      firstNightUntil?: string
    }
    /** @description Describes a HDC Licence */
    HdcLicence: {
      /**
       * Format: int64
       * @description The id for the licence
       */
      licenceId?: number
      /** @description The curfew or CAS2 address for the person */
      curfewAddress?: components['schemas']['CurfewAddress']
      /** @description The first night curfew times for the person */
      firstNightCurfewHours?: components['schemas']['FirstNight']
      /** @description The curfew times for the person following the first night */
      curfewTimes?: components['schemas']['CurfewTimes'][]
      /**
       * @description The HDC status for the person
       * @enum {string}
       */
      status: 'APPROVED' | 'NOT_A_HDC_RELEASE' | 'NOT_STARTED' | 'ELIGIBILITY_CHECKS_COMPLETE' | 'RISK_CHECKS_COMPLETE'
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  retryDlq: {
    parameters: {
      query?: never
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult']
        }
      }
    }
  }
  retryAllDlqs: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult'][]
        }
      }
    }
  }
  purgeQueue: {
    parameters: {
      query?: never
      header?: never
      path: {
        queueName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PurgeQueueResult']
        }
      }
    }
  }
  populateDeletedAtForLicences: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description This is the Id number of the last licence to be processed in the previous batch migrated */
        lastIdProcessed: number
        /** @description This is the number of licences to migrate in one batch */
        batchSize: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Migration response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MigrationBatchResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  resetLicences: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': number[]
      }
    }
    responses: {
      /** @description Information about reset licences */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResetResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getBespokeConditions: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LicenceIdBatchRequest']
      }
    }
    responses: {
      /** @description Conditions retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ConvertedLicenseBatch']
        }
      }
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ConvertedLicenseBatch']
        }
      }
    }
  }
  populateDeletedAtForLicences_1: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getSarContentByReference: {
    parameters: {
      query?: {
        /** @description NOMIS Prison Reference Number */
        prn?: string
        /** @description nDelius Case Reference Number */
        crn?: string
        /** @description Optional parameter denoting minimum date of event occurrence which should be returned in the response */
        fromDate?: string
        /** @description Optional parameter denoting maximum date of event occurrence which should be returned in the response */
        toDate?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Request successfully processed - content found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HmppsSubjectAccessRequestContent']
        }
      }
      /** @description Request successfully processed - no content found */
      204: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      /** @description Subject Identifier is not recognised by this service */
      209: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      /** @description The client does not have authorisation to make this request */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error occurred */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getDlqMessages: {
    parameters: {
      query?: {
        maxMessages?: number
      }
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetDlqResult']
        }
      }
    }
  }
  getHdcLicenceByBookingId: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookingId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Licence found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HdcLicence']
        }
      }
      /** @description Licence for this booking ID was not found. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HdcLicence']
        }
      }
      /** @description Search by crn is not supported. */
      209: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The licence data for this booking ID was not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error occurred */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}

// --- Auto-generated schema type aliases ---
export type RetryDlqResult = components['schemas']['RetryDlqResult']
export type PurgeQueueResult = components['schemas']['PurgeQueueResult']
export type MigrationBatchResponse = components['schemas']['MigrationBatchResponse']
export type ErrorResponse = components['schemas']['ErrorResponse']
export type ResetResponse = components['schemas']['ResetResponse']
export type LicenceIdBatchRequest = components['schemas']['LicenceIdBatchRequest']
export type ConvertedBespokeCondition = components['schemas']['ConvertedBespokeCondition']
export type ConvertedLicenseBatch = components['schemas']['ConvertedLicenseBatch']
export type ConvertedLicenseConditions = components['schemas']['ConvertedLicenseConditions']
export type Attachment = components['schemas']['Attachment']
export type HmppsSubjectAccessRequestContent = components['schemas']['HmppsSubjectAccessRequestContent']
export type DlqMessage = components['schemas']['DlqMessage']
export type GetDlqResult = components['schemas']['GetDlqResult']
export type CurfewAddress = components['schemas']['CurfewAddress']
export type CurfewTimes = components['schemas']['CurfewTimes']
export type FirstNight = components['schemas']['FirstNight']
export type HdcLicence = components['schemas']['HdcLicence']
