module.exports = [
    {bookingId: 1,
    offenderNo: 'A0001XX',
    firstName: 'RO Processing',
    lastName: 'Andrews',
    dateOfBirth: '22/10/1989',
    agencyLocationId: 'LT1',
    agencyLocationDesc: 'Licence Auto Test Prison',
    internalLocationDesc: 'A-1-1',
    facialImageId: 1,
    sentenceDetail:
        {bookingId: 1,
            conditionalReleaseDate: '15/10/2019',
            homeDetentionCurfewEligibilityDate: '13/07/2019'},
    stage: 'PROCESSING_RO',
    status: 'Submitted to RO'},

    {bookingId: 2,
        offenderNo: 'A0001XX',
        firstName: 'Unstarted',
        lastName: 'Andrews',
        dateOfBirth: '22/10/1989',
        agencyLocationId: 'LT1',
        agencyLocationDesc: 'Licence Auto Test Prison',
        internalLocationDesc: 'A-1-1',
        facialImageId: 1,
        sentenceDetail:
            {bookingId: 1,
                conditionalReleaseDate: '15/10/2019',
                homeDetentionCurfewEligibilityDate: '13/07/2019'},
        stage: 'UNSTARTED',
        status: 'Submitted to RO'},

    {bookingId: 3,
        offenderNo: 'A0001XX',
        firstName: 'Eligibility',
        lastName: 'Andrews',
        dateOfBirth: '22/10/1989',
        agencyLocationId: 'LT1',
        agencyLocationDesc: 'Licence Auto Test Prison',
        internalLocationDesc: 'A-1-1',
        facialImageId: 1,
        sentenceDetail:
            {bookingId: 1,
                conditionalReleaseDate: '15/10/2019',
                homeDetentionCurfewEligibilityDate: '13/07/2019'},
        stage: 'ELIGIBILITY',
        status: 'Submitted to RO'},

    {bookingId: 4,
        offenderNo: 'A0001XX',
        firstName: 'Approval',
        lastName: 'Andrews',
        dateOfBirth: '22/10/1989',
        agencyLocationId: 'LT1',
        agencyLocationDesc: 'Licence Auto Test Prison',
        internalLocationDesc: 'A-1-1',
        facialImageId: 1,
        sentenceDetail:
            {bookingId: 1,
                conditionalReleaseDate: '15/10/2019',
                homeDetentionCurfewEligibilityDate: '13/07/2019'},
        stage: 'APPROVAL',
        status: 'Submitted to RO'},

    {bookingId: 5,
        offenderNo: 'A0001XX',
        firstName: 'Approved',
        lastName: 'Andrews',
        dateOfBirth: '22/10/1989',
        agencyLocationId: 'LT1',
        agencyLocationDesc: 'Licence Auto Test Prison',
        internalLocationDesc: 'A-1-1',
        facialImageId: 1,
        sentenceDetail:
            {bookingId: 1,
                conditionalReleaseDate: '15/10/2019',
                homeDetentionCurfewEligibilityDate: '13/07/2019'},
        stage: 'DECIDED',
        status: 'Approved'},

    {bookingId: 5,
        offenderNo: 'A0001XX',
        firstName: 'Refused',
        lastName: 'Andrews',
        dateOfBirth: '22/10/1989',
        agencyLocationId: 'LT1',
        agencyLocationDesc: 'Licence Auto Test Prison',
        internalLocationDesc: 'A-1-1',
        facialImageId: 1,
        sentenceDetail:
            {bookingId: 1,
                conditionalReleaseDate: '15/10/2019',
                homeDetentionCurfewEligibilityDate: '13/07/2019'},
        stage: 'DECIDED',
        status: 'Refused'}
];
