apiVersion: v2
appVersion: "1.1"
description: A Helm chart for the HDC licences application
name: licences
version: 2.0.1

dependencies:
  - name: gotenberg
    version: "0.1.x"
    repository: file://subcharts/gotenberg
  - name: generic-prometheus-alerts
    version: 0.4.1
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
  - name: generic-data-analytics-extractor
    version: 0.1.3
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
