generic-service:
  enabled: true
  nameOverride: licences
  replicaCount: 4
  productId: 'DPS062'

  image:
    repository: quay.io/hmpps/licences
    tag: app_version
    port: 3000

  ingress:
    enabled: true
    hosts:
      - app-hostname.local # override per environment
    tlsSecretName: licences-cert
    annotations:
      external-dns.alpha.kubernetes.io/aws-weight: '100'

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  namespace_secrets:
    dps-rds-instance-output:
      DB_NAME: 'database_name'
      DB_SERVER: 'rds_instance_address'
      DB_USER: 'database_username'
      DB_PASS: 'database_password'

    licences:
      API_CLIENT_ID: 'API_CLIENT_ID'
      API_CLIENT_SECRET: 'API_CLIENT_SECRET'
      ADMIN_API_CLIENT_ID: 'ADMIN_API_CLIENT_ID'
      ADMIN_API_CLIENT_SECRET: 'ADMIN_API_CLIENT_SECRET'
      NOTIFY_API_KEY: 'NOTIFY_API_KEY'
      TAG_MANAGER_KEY: 'TAG_MANAGER_KEY'

    licences-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: APPLICATIONINSIGHTS_CONNECTION_STRING

    licences-elasticache-redis:
      REDIS_HOST: 'primary_endpoint_address'
      REDIS_AUTH_TOKEN: 'auth_token'

    licences-session-secret:
      SESSION_SECRET: 'SESSION_SECRET'

  env:
    DB_SSL_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    NODE_ENV: 'production'
    HDC_URL: 'http://licences:80'
    GOTENBERG_API_URL: 'http://licences-gotenberg'

gotenberg:
  nameOverride: gotenberg
  replicaCount: 2

  image:
    repository: thecodingmachine/gotenberg
    tag: 7.8.2
    port: 3000

  ingress:
    enabled: false

  livenessProbe:
    httpGet:
      path: /health
    periodSeconds: 30
    initialDelaySeconds: 60
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    httpGet:
      path: /health
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  podSecurityContext:
    fsGroup: 1001

  securityContext:
    runAsUser: 1001
    runAsNonRoot: true

generic-prometheus-alerts:
  targetApplication: licences
  alertSeverity: digital-prison-service-dev

generic-data-analytics-extractor:
  enabled: true
  databaseSecretName: dps-rds-instance-output
  analyticalPlatformSecretName: licences-analytical-platform-reporting-s3-bucket
  args: 'extract_psql_all_tables_to_csv.sh && transfer_local_to_s3.sh'
