---
image:
  repository: quay.io/hmpps/licences
  tag: latest
  port: 3000

generic-prometheus-alerts:
  targetApplication: licences
  alertSeverity: digital-prison-service-dev

generic-data-analytics-extractor:
  databaseSecretName: dps-rds-instance-output
  analyticalPlatformSecretName: licences-analytical-platform-reporting-s3-bucket
  enabled: true
  args: "extract_psql_all_tables_to_csv.sh && transfer_local_to_s3.sh"

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
