generic-service:
  enabled: true
  nameOverride: licences
  replicaCount: 4
  serviceAccountName: licences
  productId: "DPS062"

  image:
    repository: quay.io/hmpps/licences
    tag: app_version
    port: 3000

  ingress:
    enabled: true
    hosts:
      - app-hostname.local
    tlsSecretName: licences-cert
    annotations:
      external-dns.alpha.kubernetes.io/aws-weight: "100"

  postgresDatabaseRestore:
    enabled: true
    schedule: "30 10 * * 0"
    env:
      SCHEMA_TO_RESTORE: "probation_teams"
    namespace_secrets:
      dps-rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      dps-rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

generic-prometheus-alerts:
  targetApplication: licences
  alertSeverity: digital-prison-service-dev


generic-data-analytics-extractor:
  enabled: true
  databaseSecretName: dps-rds-instance-output
  analyticalPlatformSecretName: licences-analytical-platform-reporting-s3-bucket
  args: "extract_psql_all_tables_to_csv.sh && transfer_local_to_s3.sh"


gotenberg:
  nameOverride: gotenberg
  replicaCount: 2

  image:
    repository: thecodingmachine/gotenberg
    tag: "6.4.3"
    port: 3000

  ingress:
    enabled: false

  livenessProbe:
    httpGet:
      path: /health
      port: http

  readinessProbe:
    httpGet:
      path: /health
      port: http

  podSecurityContext:
    fsGroup: 1001

  securityContext:
    runAsUser: 1001
    runAsNonRoot: true
