module.exports = {
  NO_OFFENDER_NUMBER: 'NO_OFFENDER_NUMBER',
  NO_COM_ASSIGNED: 'NO_COM_ASSIGNED',
  STAFF_NOT_PRESENT: 'STAFF_NOT_PRESENT',
  STAFF_NOT_LINKED: 'STAFF_NOT_LINKED',
  LDU_INACTIVE: 'LDU_INACTIVE',
  COM_NOT_ALLOCATED: 'COM_NOT_ALLOCATED',
  NOTIFICATION_DATA_NOT_FOUND: 'NOTIFICATION_DATA_NOT_FOUND',
}
