generic-service:
  replicaCount: 4

  ingress:
    enabled: true
    tlsSecretName: licences-cert
    hosts:
      - licences.prison.service.justice.gov.uk
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: licences-licences-prod-green
    enable_allowlist: true

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons
      - probation

  env:
    DOMAIN: 'https://licences.prison.service.justice.gov.uk'
    NOMIS_API_URL: 'https://prison-api.prison.service.justice.gov.uk'
    NOMIS_AUTH_URL: 'https://sign-in.hmpps.service.justice.gov.uk/auth'
    GLOBAL_SEARCH_URL: 'https://digital.prison.service.justice.gov.uk/global-search'
    PUSH_TO_NOMIS: 'yes'
    REMINDERS_SCHEDULE_RO: '0 1 * * 1-5'
    SCHEDULED_JOBS_AUTOSTART: 'yes'
    SCHEDULED_JOBS_OVERLAP: '5000'
    NOTIFY_ACTIVE_TEMPLATES: 'CA_RETURN,CA_DECISION,RO_NEW,DM_NEW,DM_TO_CA_RETURN'
    DELIUS_API_URL: 'https://hdc-licences-and-delius.hmpps.service.justice.gov.uk'
    HDC_API_URL: 'https://hdc-api.hmpps.service.justice.gov.uk'
    PROBATION_TEAMS_API_URL: 'https://probation-teams.prison.service.justice.gov.uk'
    PRISONER_SEARCH_API_URL: 'https://prisoner-search.prison.service.justice.gov.uk'
    PROBATION_SEARCH_API_URL: 'https://hdc-licences-and-delius.hmpps.service.justice.gov.uk'
    MANAGE_USERS_API_URL: 'https://manage-users-api.hmpps.service.justice.gov.uk'
    EXIT_LOCATION_URL: 'https://digital.prison.service.justice.gov.uk/'
    TOKENVERIFICATION_API_URL: 'https://token-verification-api.prison.service.justice.gov.uk'
    TOKENVERIFICATION_API_ENABLED: 'true'
    FEEDBACK_SUPPORT_URL: 'https://support.hmpps.service.justice.gov.uk/feedback-and-support'
    CREATE_AND_VARY_A_LICENCE_VARY_CASELOAD_URL: 'https://create-and-vary-a-licence.hmpps.service.justice.gov.uk/licence/vary/caseload'
    LICENCE_RISK_MANAGEMENT_VERSION: '3'
    CURFEW_ADDRESS_REVIEW_VERSION: '2'
    LICENCE_POSTPONE_VERSION: '2'
    COM_NOT_ALLOCATED_BLOCK_ENABLED: 'true'
    CA_REPORTS_LINK_ENABLED: 'true'
    HDC_IN_CVL_EARLY_ADOPTER_ENABLED: 'false'
    HDC_IN_CVL_EARLY_ADOPTER_PROVIDER_CODES: 'N59'

  postgresDatabaseRestore:
    enabled: true
    schedule: '30 6-21/4 * * 1-5'
    env:
      SCHEMA_TO_RESTORE: 'public'
      MIGRATIONS_VENDOR: 'knex'
    namespace_secrets:
      dps-rds-instance-output:
        DB_NAME: 'database_name'
        DB_USER: 'database_username'
        DB_PASS: 'database_password'
        DB_HOST: 'rds_instance_address'
      dps-rds-instance-output-preprod:
        DB_NAME_PREPROD: 'database_name'
        DB_USER_PREPROD: 'database_username'
        DB_PASS_PREPROD: 'database_password'
        DB_HOST_PREPROD: 'rds_instance_address'

gotenberg:
  replicaCount: 4

generic-prometheus-alerts:
  targetApplication: licences
  alertSeverity: cvl-alerts
