# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: docker.io/mojdigitalstudio/licences
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: true
  host: licences.prison.service.justice.gov.uk
  cert_secret: licences-cert
  path: /

env:
  NOMIS_API_URL: "https://gateway.prod.nomis-api.service.hmpps.dsd.io/elite2api/api" 
  NOMIS_AUTH_URL: "https://gateway.prod.nomis-api.service.hmpps.dsd.io/auth"
  GLOBAL_SEARCH_URL: "https://whereabouts.prison.service.justice.gov.uk/global-search"
  AUTH_STRATEGY: "oauth"
  PUSH_TO_NOMIS: "yes"
  REMINDERS_SCHEDULE_RO: "0 1 * * 1-5"
  SCHEDULED_JOBS_AUTOSTART: "yes"
  SCHEDULED_JOBS_OVERLAP: "5000"
  NOTIFY_ACTIVE_TEMPLATES: "CA_RETURN,CA_DECISION,RO_NEW,DM_NEW,DM_TO_CA_RETURN" 
  RO_SERVICE_TYPE: "DELIUS"
  DELIUS_API_URL: "https://community-api.service.hmpps.dsd.io/communityapi/api"

whitelist:
  office: "217.33.148.210/32"
  quantum: "62.25.109.197/32"
  quantum_alt: "212.137.36.230/32"
  health-kick: "35.177.252.195/32"
  digitalprisons1: "52.56.112.98/32"
  digitalprisons2: "52.56.118.154/32"
  mojvpn: "81.134.202.29/32"
  j5-phones-1: "35.177.125.252/32"
  j5-phones-2: "35.177.137.160/32"
  sodexo-northumberland: "88.98.48.10/32"
  thameside-private-prison: "217.22.14.151/32"
  durham-tees-valley: "51.179.193.241/32"
  ark-nps-hmcts-ttp1: "195.59.75.0/24"
  ark-nps-hmcts-ttp2: "194.33.192.0/25"
  ark-nps-hmcts-ttp3: "194.33.193.0/25"
  ark-nps-hmcts-ttp4: "194.33.196.0/25"
  ark-nps-hmcts-ttp5: "194.33.197.0/25"
  oakwood: "194.176.200.113/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
