# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/licences
  tag: latest
  port: 3000

# Supplies values to the nested gotenberg chart. https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
gotenberg:
  replicaCount: 4
  image:
    repository: thecodingmachine/gotenberg
    tag: 6.4.3
    port: 3000

ingress:
  enabled: true
  enable_allowlist: true
  host: licences-preprod.prison.service.justice.gov.uk
  cert_secret: licences-cert
  path: /
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: licences-licences-preprod-green

env:
  NOMIS_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
  NOMIS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
  GLOBAL_SEARCH_URL: "https://digital-preprod.prison.service.justice.gov.uk/global-search"
  PUSH_TO_NOMIS: "yes"
  REMINDERS_SCHEDULE_RO: "0 1 * * 1-5"
  SCHEDULED_JOBS_AUTOSTART: "yes"
  SCHEDULED_JOBS_OVERLAP: "5000"
  NOTIFY_ACTIVE_TEMPLATES: "CA_RETURN,CA_DECISION,RO_NEW,DM_NEW,DM_TO_CA_RETURN"
  DELIUS_API_URL: "https://hdc-licences-and-delius-preprod.hmpps.service.justice.gov.uk"
  PROBATION_TEAMS_API_URL: "https://probation-teams-preprod.prison.service.justice.gov.uk"
  PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
  MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
  EXIT_LOCATION_URL: "https://digital-preprod.prison.service.justice.gov.uk/"
  TOKENVERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
  TOKENVERIFICATION_API_ENABLED: true
  FEEDBACK_SUPPORT_URL: "https://support-preprod.hmpps.service.justice.gov.uk/feedback-and-support"
  LICENCE_RISK_MANAGEMENT_VERSION: '3'
  CURFEW_ADDRESS_REVIEW_VERSION: '2'
  LICENCE_POSTPONE_VERSION: '2'
  COM_NOT_ALLOCATED_BLOCK_ENABLED: false

allowlist:
  office: "217.33.148.210/32"
  quantum: "62.25.109.197/32"
  quantum_alt: "212.137.36.230/32"
  health-kick: "35.177.252.195/32"
  digitalprisons1: "52.56.112.98/32"
  digitalprisons2: "52.56.118.154/32"
  mojvpn: "81.134.202.29/32"
  j5-phones-1: "35.177.125.252/32"
  j5-phones-2: "35.177.137.160/32"
  sodexo-bronzefield: "51.148.9.201/32"
  sodexo-northumberland: "88.98.48.10/32"
  sodexo-northumberland2: "51.148.47.137/32"
  sodoxeo-forest-bank: "51.155.85.249/32"
  sodexo-peterborough: "51.155.55.241/32"
  serco-1: "217.22.14.151/32"
  serco-2: "128.77.110.45/32"
  durham-tees-valley: "51.179.197.1/32"
  oakwood-01: "217.161.76.184/29"
  oakwood-02: "217.161.76.192/29"
  oakwood-1: "217.161.76.187/32"
  oakwood-2: "217.161.76.195/32"
  oakwood-3: "217.161.76.186/32"
  oakwood-4: "217.161.76.194/32"
  dxc-mitcheldean: "195.92.38.16/28"
  ark-dom1-ttp1: "195.59.75.0/24"
  ark-dom1-farnborough: "194.33.192.0/24"
  ark-dom1-farnborough-psn: "51.247.3.0/24"
  ark-dom1-corsham: "194.33.196.0/24"
  ark-dom1-corsham-psn: "51.247.4.0/24"
  ark-dom1-non-live-1: "194.33.193.0/25"
  ark-dom1-non-live-2: "194.33.197.0/25"
  moj-official-ark-c-expo-e: "51.149.249.0/29"
  moj-official-ark-c-vodafone: "194.33.248.0/29"
  moj-official-ark-f-vodafone: "194.33.249.0/29"
  moj-official-ark-f-expo-e: "51.149.249.32/29"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
  interservfls: "51.179.196.131/32"
  sodexo1: "80.86.46.16/32"
  sodexo2: "80.86.46.17/32"
  sodexo3: "80.86.46.18/32"
  dxc_webproxy1: "195.92.38.20/32"
  dxc_webproxy2: "195.92.38.21/32"
  dxc_webproxy3: "195.92.38.22/32"
  dxc_webprox23: "195.92.38.23/32"
  moj-official-tgw-prod: "51.149.250.0/24"
  moj-official-tgw-preprod: "51.149.251.0/24"
  crc-rrp: "62.253.83.37/32"
  crc-pp-wwm: "5.153.255.210/32"
  fivewells-1: "20.49.214.199/32"
  fivewells-2: "20.49.214.228/32"
  fivewells-3: "195.89.157.56/29"
  fivewells-4: "195.59.215.184/29"
  global-protect: "35.176.93.186/32"
  petty-france-wifi: "213.121.161.112/28"
  vodafone-dia-1: "194.33.200.0/21"
  vodafone-dia-2: "194.33.216.0/24"
  vodafone-dia-3: "194.33.217.0/24"
  vodafone-dia-4: "194.33.218.0/24"
  palo-alto-prisma-corporate: "128.77.75.64/26"

generic-prometheus-alerts:
  alertSeverity: cvl-alerts-non-prod
