generic-service:
  replicaCount: 4

  ingress:
    enabled: true
    hosts:
      - licences-preprod.prison.service.justice.gov.uk
    tlsSecretName: licences-cert
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: licences-licences-preprod-green
    enable_allowlist: true

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons
      - probation

  env:
    DOMAIN: 'https://licences-preprod.prison.service.justice.gov.uk'
    NOMIS_API_URL: 'https://prison-api-preprod.prison.service.justice.gov.uk'
    NOMIS_AUTH_URL: 'https://sign-in-preprod.hmpps.service.justice.gov.uk/auth'
    GLOBAL_SEARCH_URL: 'https://digital-preprod.prison.service.justice.gov.uk/global-search'
    PUSH_TO_NOMIS: 'yes'
    REMINDERS_SCHEDULE_RO: '0 1 * * 1-5'
    SCHEDULED_JOBS_AUTOSTART: 'yes'
    SCHEDULED_JOBS_OVERLAP: '5000'
    NOTIFY_ACTIVE_TEMPLATES: 'CA_RETURN,CA_DECISION,RO_NEW,DM_NEW,DM_TO_CA_RETURN'
    DELIUS_API_URL: 'https://hdc-licences-and-delius-preprod.hmpps.service.justice.gov.uk'
    HDC_API_URL: 'https://hdc-api-preprod.hmpps.service.justice.gov.uk'
    PROBATION_TEAMS_API_URL: 'https://probation-teams-preprod.prison.service.justice.gov.uk'
    PRISONER_SEARCH_API_URL: 'https://prisoner-search-preprod.prison.service.justice.gov.uk'
    PROBATION_SEARCH_API_URL: 'https://hdc-licences-and-delius-preprod.hmpps.service.justice.gov.uk'
    MANAGE_USERS_API_URL: 'https://manage-users-api-preprod.hmpps.service.justice.gov.uk'
    EXIT_LOCATION_URL: 'https://digital-preprod.prison.service.justice.gov.uk/'
    TOKENVERIFICATION_API_URL: 'https://token-verification-api-preprod.prison.service.justice.gov.uk'
    TOKENVERIFICATION_API_ENABLED: 'true'
    FEEDBACK_SUPPORT_URL: 'https://support-preprod.hmpps.service.justice.gov.uk/feedback-and-support'
    LICENCE_RISK_MANAGEMENT_VERSION: '3'
    CURFEW_ADDRESS_REVIEW_VERSION: '2'
    LICENCE_POSTPONE_VERSION: '2'
    COM_NOT_ALLOCATED_BLOCK_ENABLED: 'true'
    CA_REPORTS_LINK_ENABLED: 'true'
    HDC_IN_CVL_EARLY_ADOPTER_ENABLED: 'true'

generic-prometheus-alerts:
  alertSeverity: cvl-alerts-non-prod
