name: Build and test node

on:
  workflow_call:
    inputs:
      test_results_artifact_name:
        description: 'Name of uploaded test results artifact; must be unique across pipeline (eg. in matrix strategies for parallelised tests)'
        required: false
        type: string
        default: 'npm_gotenberg_artifacts'
      node_version_file:
        description: 'Passed to setup-node action to specify where to source the version of node from'
        required: false
        type: string
        default: '.nvmrc'

permissions:
  contents: read

jobs:
  node-unit-test:
    name: Running gotenberg tests
    runs-on: ubuntu-latest
    services:
      gotenberg:
        image: thecodingmachine/gotenberg:7.8.2
        ports:
          - 3001:3000
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ${{ inputs.node_version_file }}
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        env:
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json', '!**/node_modules/**') }}
      - name: download the artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: npm_build_artifacts
      - name: gotenberg tests
        id: unit-tests
        shell: bash
        run: |
          npm run integration-test
        # continue-on-error: true
        # Replacing the above with if: always()
      - name: upload the artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ inputs.test_results_artifact_name }}
          path: test_results
      - name: publish test report
        if: ${{ !cancelled() && github.event.repository.visibility == 'public' }}
        uses: dorny/test-reporter@df6247429542221bc30d46a036ee47af1102c451 # v2
        with:
          artifact: ${{ inputs.test_results_artifact_name }}
          name: Test Report
          path: 'jest/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
          list-suites: 'failed'
          list-tests: 'failed'
      - name: fail the action if the tests failed
        if: ${{ steps.unit-tests.outcome == 'failure' }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            core.setFailed('Gotenberg tests failed')
